export const TEXTS = {
    SIGNUP: {
        title: "Sign Up",
        subtitle: "Sign up to create an account",
        fullNameLabel: "Full Name",
        fullNamePlaceholder: "John Doe",
        fullNameRequired: "Full name is required",
        emailLabel: "Email",
        emailPlaceholder: "Hs7oJ@example.com",
        emailRequired: "Email is required",
        passwordLabel: "Password",
        passwordPlaceholder: "Password",
        passwordRequired: "Password is required",
        phoneNumberLabel: "Phone No.",
        phoneNumberPlaceholder: "1234567890",
        phoneNumberRequired: "Phone number is required",
        countryCode: "IN +91",
        country: "Country",
        buttonTitle: "Sign Up",
        continueWith: "or continue with",
        footerText: "Do You have an account?",
        signIn: "sign in",
        errors: {
            fullNameRequired: "Full name is required",
            fullNameMinLength: "Name must be at least 3 characters",
            emailRequired: "Email is required",
            invalidEmail: "Please enter valid email",
            phoneRequired: "Phone number is required",
            invalidPhone: "Please enter valid phone number",
            passwordRequired: "Password is required",
            passwordMinLength: "Password must be at least 6 characters",
        },
    },
    LOGIN: {
        title: "Login",
        subtitle: "Login to your account",
        emailLabel: "Email",
        emailPlaceholder: "Hs7oJ@example.com",
        emailRequired: "Email is required",
        passwordLabel: "Password",
        passwordPlaceholder: "Password",
        passwordRequired: "Password is required",
        buttonTitle: "Login",
        continueWith: "or continue with",
        footerText: "Don't have an account?",
        signUp: "sign up",

        errors: {
            emailRequired: "Email is required",
            invalidEmail: "Please enter valid email",
            passwordRequired: "Password is required",
            passwordMinLength: "Password must be at least 6 characters",
        },
    },
    Index: {
        Category: "Category",
        Products: "Products",
        Filters: "Filters",
    },
    ProductDetails: {
        addToCart: "Add To Cart",
        buyNow: "Buy Now",
        title: "Product Details",
        IN_STOCK: "In Stock",
        OUT_OF_STOCK: "Out of Stock",
        reviews: "reviews"
    },
    ACCOUNT: {
        TITLE: "Account Details",
        SUBTITLE: "Manage your account details here",
        FULL_NAME: "Full Name: ",
        EMAIL: "Email: ",
        PHONE: "Phone Number: ",
    },
    ADDRESS: {
        TITLE: "Address Details",
        SUBTITLE: "Manage your saved addresses here",
        HOME: "Primary Address",
        ADD_NEW: "Add New Address",
        OTHER: "Other Address",
    },
    SECURITY: {
        TITLE: "Security",
        SUBTITLE: "Manage your account security settings",
        CHANGE_PASSWORD: "Change Password",
        CHANGE_PASSWORD_SUBTITLE:
            "Ensure your account is secure by updating your password regularly.",
        OLD_PASSWORD: "Old Password",
        NEW_PASSWORD: "New Password",
        CONFIRM_PASSWORD: "Confirm Password",
        UPDATE_PASSWORD: "Update Password",
        FACE_ID: "Face ID Security",
        FACE_ID_SUBTITLE:
            "Enable Face ID authentication for faster and secure login.",
        ENABLED: "Enabled",
        DISABLED: "Disabled",
        LOGOUT: "Logout",
        LOGOUT_SUBTITLE:
            "Sign out of your account from this device.",
        ERRORS: {
            OLD_PASSWORD_REQUIRED: "Old password is required",
            NEW_PASSWORD_REQUIRED: "New password is required",
            CONFIRM_PASSWORD_REQUIRED: "Confirm password is required",
            PASSWORD_MISMATCH: "Passwords do not match",
            PASSWORD_MIN_LENGTH: "Password must be at least 6 characters",
        },
    },
    EDIT_PROFILE: {
        TITLE: "User Details",
        FULL_NAME_LABEL: "Full Name",
        FULL_NAME_PLACEHOLDER: "Enter full name",
        PHONE_LABEL: "Phone No.",
        PHONE_PLACEHOLDER: "Enter phone number",
        EMAIL_LABEL: "Email",
        EMAIL_PLACEHOLDER: "Enter email",
        CHOOSE_FILE: "Choose File",
        UPDATE: "Update",
        UPLOAD: "Upload Photo",
        SUCCESS: "Profile updated successfully",
        ERRORS: {
            FULL_NAME_REQUIRED:
                "Full name is required",
            PHONE_REQUIRED:
                "Phone number is required",
            EMAIL_REQUIRED:
                "Email is required",
            ONE_FIELD_REQUIRED: "At least one field is required",
        },
    },
    CHECKOUT: {
        SELECT_DELIVERY_ADDRESS: "Select Delivery Address",
        ADD_NEW_ADDRESS: "+ Add New Address",
        PRICE_DETAILS: "Price Details",
        TOTAL_PRODUCTS_PRICE: "Total Products Price:",
        TOTAL_DISCOUNT: "Total Discount:",
        TOTAL_PRICE: "Total Price:",
        CONTINUE: "Continue",
        NO_ADDRESS_TITLE: "No Address Found",
        NO_ADDRESS_SUBTITLE:
            "Please add a delivery address to continue checkout.",
        PAYMENT_ORDER_DETAILS: "Payment & Order Details",
        PAYMENT_STATUS: "Payment Status:",
        PAYMENT_METHOD: "Payment Method:",
        ORDER_PRICE: "Order Price:",
        CART_TOTAL: "Cart Total:",
        DELIVERY_ADDRESS: "Delivery Address",
    },
    ABOUT: {
        TITLE: "About",
        SUBTITLE: "Learn more about the app and developer",
        APP_NAME: "Byte Bazaar",
        APP_VERSION: "Version 1.0.0",
        DEVELOPER: "Developer",
        DEVELOPER_NAME: "Hardip Solanki",
        ROLE: "React Native Developer",
        GITHUB: "GitHub",
        GITHUB_USERNAME: "hardipsolanki22",
        BIO:
            "Passionate React Native developer focused on building scalable, high-performance mobile applications with clean architecture and modern UI.",
        CONTACT_TITLE: "Connect",
        APPLICATION: "Application",
        APP_NAME_LABEL: "App Name",
        VERSION_LABEL: "Version",
        DEVELOPER_LABEL: "Developer",
    },
    ORDER: {
        STATUS: "Status",
        ITEMS: " items",
    },
    CART: {
        EMPTY_CART_TITLE: "Your cart is empty",
        EMPTY_CART_SUBTITLE: "Add some items to get started",
        CHECKOUT: "Checkout",
        PRODUCTS: "Products",
        PRICE_DETAILS: "Price Details",
        TOTAL_DISCOUNT: "Total Discount",
        TOTAL_PRICE: "Total Price",
    },

}